import {PLANETS,type PlanetId} from './model.ts';
import {TITANS} from './titan-content.ts';
import {SIZE_FACTORS,sized,sizeFactor} from './creature-sizes.ts';

export type EnemyBehavior='hopper'|'melee'|'charger'|'rooted'|'shooter'|'boss';
export interface EnemyDefinition {name:string;hp:number;damage:number;speed:number;reach:number;sight:number;xp:number;radius:number;behavior:EnemyBehavior;family:string;color:string;accent:string;cooldown:number;windup:number;boss:boolean;titan?:boolean;flying?:boolean;stealth?:number;aquatic?:boolean}
function creature(name:string,hp:number,damage:number,speed:number,xp:number,family:string,color:string,behavior:EnemyBehavior='melee',extra:Partial<EnemyDefinition>={}):EnemyDefinition{
  return {name,hp,damage,speed,xp,family,color,accent:'#fff1cf',behavior,reach:1.6,sight:10,radius:.7,cooldown:1.5,windup:.45,boss:false,...extra};
}
function boss(name:string,hp:number,damage:number,xp:number,family:string,color:string,extra:Partial<EnemyDefinition>={}){
  return creature(name,hp,damage,2.5,xp,family,color,'boss',{reach:2.6,sight:13,radius:1.4,cooldown:2.2,windup:.6,boss:true,...extra});
}
// Rule values are factual observations; meshes and behavior code are original.
export const ENEMY_TYPES:Record<string,EnemyDefinition>={
  mushroom:creature('Grumpy Mushroom',45,6,2.4,8,'mushroom','#ff4d5e','hopper',{radius:.55,reach:1.3,sight:8}),
  boar:creature('Wild Boar',85,10,3,14,'quadruped','#a9744f','charger',{radius:.8,cooldown:2.6,windup:.7}),
  bee:creature('Cross Wasp',55,8,3.8,12,'winged','#ffd23f','melee',{radius:.5,reach:1.4,flying:true,cooldown:1.1,windup:.3}),
  forest_raptor:creature('Great Forest Hawk',160,14,4.2,36,'winged','#96714c','charger',{radius:.8,reach:1.9,sight:13,flying:true,accent:'#e8d2a6',cooldown:2.8,windup:.75}),
  wolf:creature('Grey Wolf',100,12,4.3,22,'quadruped','#8f9bb3','melee',{sight:12,cooldown:1.3,windup:.35}),
  chomper:creature('Snapping Flower',120,14,0,20,'flower','#58c24a','rooted',{radius:.8,reach:2.5,sight:7,accent:'#ff4f7a',cooldown:1.7,windup:.55}),
  frog:creature('Poison Frog',70,10,2.8,16,'frog','#6fd35a','hopper',{radius:.6,accent:'#b27dff',cooldown:1.3}),
  cactus:creature('Prickly Cactus',140,15,0,30,'cactus','#4cb86b','shooter',{radius:.75,reach:11,sight:11,cooldown:2.1,windup:.6}),
  crab:creature('Stone Crab',130,14,2.6,26,'crab','#ff6a4d','melee',{radius:.8,windup:.5}),
  bear:boss('King Bear',800,26,300,'bear','#8b5a3c'),
  treant:boss('Ancient Treant',700,22,240,'treant','#8a5a3b',{speed:2.2,accent:'#4fbf5a'}),
  croc:boss('Crocodile King',850,25,280,'quadruped','#4f9e5a',{speed:2.6,reach:2.7}),
  mushking:boss('Mushroom King',650,20,260,'mushroom','#e95685'),
  jelly:creature('Jelly Jumper',60,8,2.6,12,'blob','#ff6fae','hopper',{radius:.6,reach:1.3}),
  gummy:creature('Gummy Hound',95,11,4,20,'quadruped','#8ff0d0'),
  lollipop:creature('Sugar Shooter',110,13,0,26,'lollipop','#ff8fcf','shooter',{reach:11,sight:11,cooldown:2,windup:.55}),
  bunny:creature('Marshmallow Bunny',65,9,3.2,14,'bunny','#fff0f6','hopper',{radius:.55,reach:1.3}),
  chocobeetle:creature('Chocolate Beetle',120,13,3.2,24,'crab','#6a3a24','charger',{radius:.75,cooldown:2.4,windup:.6}),
  cake:boss('Cake King',900,24,380,'cake','#fff5fb',{accent:'#ff3355'}),
  gingerbread:boss('Gingerbread Giant',850,24,360,'biped','#c9783a'),
  jellyqueen:boss('Jelly Queen',1100,26,440,'blob','#e75cad'),
  snowball:creature('Rolling Snowball',70,9,2.8,16,'blob','#f6fbff','hopper',{radius:.6,reach:1.3}),
  penguin:creature('Penguin Warrior',110,13,3.6,24,'penguin','#34405a','melee',{radius:.65,accent:'#f6fbff',cooldown:1.2}),
  icebloom:creature('Ice Blossom',130,15,0,26,'flower','#9fe8ff','rooted',{radius:.8,reach:2.5,sight:7,accent:'#ffffff'}),
  seal:creature('Ice Seal',120,13,3,24,'quadruped','#9fb4cc','charger',{radius:.75,cooldown:2.4,windup:.6}),
  owl:creature('Snow Owl',80,11,3.6,20,'winged','#f4f7fb','melee',{radius:.55,flying:true,sight:12}),
  yeti:boss('Snow Yeti',1000,28,480,'bear','#eef4ff',{accent:'#a8c8ff'}),
  mammoth:boss('Ice Mammoth',1100,30,500,'quadruped','#8a5a3b',{radius:1.8,reach:3,speed:2.4}),
  frostowl:boss('Frost Owl',1300,30,580,'winged','#cee8ff',{flying:true}),
  magmaslime:creature('Magma Slime',80,11,2.7,20,'blob','#ff6a2b','hopper',{radius:.6,reach:1.3,accent:'#ffc23d'}),
  minislime:creature('Tiny Magma Slime',24,5,3.3,6,'blob','#ff984a','hopper',{radius:.38,reach:1.1}),
  firelizard:creature('Fire Lizard',120,14,3.4,28,'quadruped','#ff7a45','charger',{radius:.8,cooldown:2.4,windup:.6}),
  volcano:creature('Little Volcano',150,17,0,34,'volcano','#4a3f4f','shooter',{radius:.75,reach:11,sight:11,accent:'#ff6a2b',cooldown:2}),
  firebat:creature('Fire Bat',70,11,4.6,20,'winged','#5a3a78','charger',{radius:.55,sight:13,flying:true,accent:'#ff6a2b',cooldown:2.2}),
  magmacrab:creature('Magma Crab',160,17,2.6,32,'crab','#4a3f4f','melee',{radius:.8,accent:'#ff6a2b'}),
  magmaturtle:creature('Magma Turtle',260,20,1.6,46,'turtle','#4a3f4f','charger',{radius:1,reach:1.9,accent:'#ff6a2b',cooldown:2.8,windup:.8}),
  lavaworm:creature('Lava Worm',190,22,5.5,44,'worm','#b0402a','charger',{reach:1.9,sight:14,cooldown:3.2,windup:1.2}),
  golem:boss('Magma Golem',1200,32,600,'biped','#5a4a58',{radius:1.5,reach:2.7,accent:'#ff6a2b'}),
  dragon:boss('Volcano Dragon',2600,36,1400,'dragon','#e0443a',{radius:1.6,reach:3,sight:18,speed:3,flying:true,accent:'#ffd27a'}),
  toysoldier:creature('Tin Soldier',75,10,2.8,18,'biped','#ed6a7e'),
  windmouse:creature('Clockwork Mouse',85,11,4.2,20,'quadruped','#90b8f0','charger'),
  jackbox:creature('Jack-in-the-Box',100,13,0,24,'jackbox','#c19bff','shooter',{reach:10}),
  robot:boss('Giant Toy Robot',950,26,400,'robot','#81bfe6'),
  monkey:creature('Jungle Monkey',105,12,3.8,24,'biped','#bb8c5e'),
  snake:creature('Emerald Snake',125,14,3.5,28,'worm','#78c854','charger'),
  chameleon:creature('Hidden Chameleon',150,16,3.7,32,'quadruped','#67a978'),
  flytrap:creature('Giant Flytrap',180,18,0,36,'flower','#48b43b','rooted',{reach:2.8,radius:.9,accent:'#ee6998'}),
  gorilla:boss('Jungle Gorilla',1500,32,700,'bear','#534c60',{radius:1.6}),
  jellyzap:creature('Electric Jellyfish',140,18,2.6,38,'blob','#8bcfea','shooter',{reach:9}),
  hammershark:creature('Hammerhead Shark',220,22,4.8,48,'quadruped','#6d9db4','charger',{radius:1}),
  urchin:creature('Coral Urchin',190,20,0,42,'cactus','#b47db8','shooter',{reach:11}),
  leviathan:boss('Ocean Leviathan',2000,35,1000,'dragon','#557ebe',{radius:1.8,reach:3}),
  cloudsheep:creature('Cloud Sheep',170,20,3,44,'quadruped','#f3f4ff'),
  thunderbird:creature('Thunderbird',180,22,4.5,50,'winged','#e6c955','charger',{flying:true}),
  windspirit:creature('Wind Spirit',150,23,0,48,'blob','#bdebee','shooter',{reach:12,flying:true}),
  phoenix:boss('Thunder Phoenix',2300,38,1200,'winged','#efa864',{flying:true,reach:3}),
  wisp:creature('Night Wisp',190,23,3.1,54,'blob','#75c9ed','hopper'),
  spider:creature('Shadow Spider',240,25,4,62,'crab','#664e8c','charger'),
  demoneye:creature('Watchful Eye',220,26,0,66,'eye','#df739f','shooter',{reach:12}),
  shadowlord:boss('Shadow Lord',2800,42,1500,'biped','#58476f',{radius:1.7,reach:3,accent:'#be91e6'}),
};

Object.assign(ENEMY_TYPES,TITANS);

export const HOME_SPAWNS:Record<string,Array<[string,number]>>={forest:[['mushroom',20],['boar',12],['bee',6]],meadow:[['mushroom',12],['boar',8],['bee',12]],swamp:[['chomper',14],['wolf',10],['frog',12],['mushroom',6]],canyon:[['cactus',14],['wolf',8],['crab',12]]};
/** Append after existing bosses/Titan: their durable combat identities must not move. */
export const FOREST_RAPTOR_COUNT=6;
export const PLANET_SPAWNS=Object.fromEntries(Object.entries(PLANETS).map(([id,planet])=>[id,planet.spawns])) as Partial<Record<PlanetId,Array<[string,number]>>>;
export const PLANET_BOSSES=Object.fromEntries(Object.entries(PLANETS).map(([id,planet])=>[id,planet.bosses])) as Partial<Record<PlanetId,string[]>>;

// Factual combat parameters; the catalog's original geometry and animation families remain independent.
const combatRules:Record<string,Partial<EnemyDefinition>>={
  "mushroom": {
    "hp": 45,
    "damage": 6,
    "speed": 2.4,
    "reach": 1.3,
    "sight": 8,
    "xp": 8,
    "radius": 0.55,
    "cooldown": 1.5,
    "windup": 0.45,
    "behavior": "hopper"
  },
  "boar": {
    "hp": 85,
    "damage": 10,
    "speed": 3,
    "reach": 1.5,
    "sight": 10,
    "xp": 14,
    "radius": 0.8,
    "cooldown": 2.6,
    "windup": 0.7,
    "behavior": "charger"
  },
  "chomper": {
    "hp": 120,
    "damage": 14,
    "speed": 0,
    "reach": 2.5,
    "sight": 7,
    "xp": 20,
    "radius": 0.8,
    "cooldown": 1.7,
    "windup": 0.55,
    "behavior": "rooted"
  },
  "wolf": {
    "hp": 100,
    "damage": 12,
    "speed": 4.3,
    "reach": 1.6,
    "sight": 12,
    "xp": 22,
    "radius": 0.7,
    "cooldown": 1.3,
    "windup": 0.35,
    "behavior": "melee"
  },
  "cactus": {
    "hp": 140,
    "damage": 15,
    "speed": 0,
    "reach": 11,
    "sight": 11,
    "xp": 30,
    "radius": 0.75,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "shooter"
  },
  "bear": {
    "hp": 800,
    "damage": 26,
    "speed": 2.5,
    "reach": 2.6,
    "sight": 13,
    "xp": 300,
    "radius": 1.4,
    "cooldown": 2.2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "jelly": {
    "hp": 60,
    "damage": 8,
    "speed": 2.6,
    "reach": 1.3,
    "sight": 9,
    "xp": 12,
    "radius": 0.6,
    "cooldown": 1.4,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "gummy": {
    "hp": 95,
    "damage": 11,
    "speed": 4,
    "reach": 1.6,
    "sight": 11,
    "xp": 20,
    "radius": 0.7,
    "cooldown": 1.3,
    "windup": 0.35,
    "behavior": "melee"
  },
  "lollipop": {
    "hp": 110,
    "damage": 13,
    "speed": 0,
    "reach": 11,
    "sight": 11,
    "xp": 26,
    "radius": 0.7,
    "cooldown": 2,
    "windup": 0.55,
    "behavior": "shooter"
  },
  "cake": {
    "hp": 900,
    "damage": 24,
    "speed": 2.4,
    "reach": 2.6,
    "sight": 13,
    "xp": 380,
    "radius": 1.4,
    "cooldown": 2.2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "snowball": {
    "hp": 70,
    "damage": 9,
    "speed": 2.8,
    "reach": 1.3,
    "sight": 9,
    "xp": 16,
    "radius": 0.6,
    "cooldown": 1.4,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "penguin": {
    "hp": 110,
    "damage": 13,
    "speed": 3.6,
    "reach": 1.6,
    "sight": 11,
    "xp": 24,
    "radius": 0.65,
    "cooldown": 1.2,
    "windup": 0.35,
    "behavior": "melee"
  },
  "icebloom": {
    "hp": 130,
    "damage": 15,
    "speed": 0,
    "reach": 2.5,
    "sight": 7,
    "xp": 26,
    "radius": 0.8,
    "cooldown": 1.6,
    "windup": 0.5,
    "behavior": "rooted"
  },
  "yeti": {
    "hp": 1000,
    "damage": 28,
    "speed": 2.6,
    "reach": 2.6,
    "sight": 13,
    "xp": 480,
    "radius": 1.4,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "magmaslime": {
    "hp": 80,
    "damage": 11,
    "speed": 2.7,
    "reach": 1.3,
    "sight": 9,
    "xp": 20,
    "radius": 0.6,
    "cooldown": 1.3,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "minislime": {
    "hp": 24,
    "damage": 5,
    "speed": 3.3,
    "reach": 1.1,
    "sight": 11,
    "xp": 6,
    "radius": 0.38,
    "cooldown": 1.1,
    "windup": 0.3,
    "behavior": "hopper"
  },
  "magmaturtle": {
    "hp": 260,
    "damage": 20,
    "speed": 1.6,
    "reach": 1.9,
    "sight": 9,
    "xp": 46,
    "radius": 1,
    "cooldown": 2.8,
    "windup": 0.8,
    "behavior": "charger"
  },
  "lavaworm": {
    "hp": 190,
    "damage": 22,
    "speed": 5.5,
    "reach": 1.9,
    "sight": 14,
    "xp": 44,
    "radius": 0.7,
    "cooldown": 3.2,
    "windup": 1.2,
    "behavior": "charger"
  },
  "firelizard": {
    "hp": 120,
    "damage": 14,
    "speed": 3.4,
    "reach": 1.5,
    "sight": 11,
    "xp": 28,
    "radius": 0.8,
    "cooldown": 2.4,
    "windup": 0.6,
    "behavior": "charger"
  },
  "volcano": {
    "hp": 150,
    "damage": 17,
    "speed": 0,
    "reach": 11,
    "sight": 11,
    "xp": 34,
    "radius": 0.75,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "shooter"
  },
  "bee": {
    "hp": 55,
    "damage": 8,
    "speed": 3.8,
    "reach": 1.4,
    "sight": 10,
    "xp": 12,
    "radius": 0.5,
    "cooldown": 1.1,
    "windup": 0.3,
    "behavior": "melee"
  },
  "frog": {
    "hp": 70,
    "damage": 10,
    "speed": 2.8,
    "reach": 1.4,
    "sight": 9,
    "xp": 16,
    "radius": 0.6,
    "cooldown": 1.3,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "crab": {
    "hp": 130,
    "damage": 14,
    "speed": 2.6,
    "reach": 1.6,
    "sight": 9,
    "xp": 26,
    "radius": 0.8,
    "cooldown": 1.5,
    "windup": 0.5,
    "behavior": "melee"
  },
  "treant": {
    "hp": 700,
    "damage": 22,
    "speed": 2.2,
    "reach": 2.6,
    "sight": 12,
    "xp": 240,
    "radius": 1.4,
    "cooldown": 2.3,
    "windup": 0.6,
    "behavior": "boss"
  },
  "croc": {
    "hp": 850,
    "damage": 25,
    "speed": 2.6,
    "reach": 2.7,
    "sight": 12,
    "xp": 280,
    "radius": 1.4,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "bunny": {
    "hp": 65,
    "damage": 9,
    "speed": 3.2,
    "reach": 1.3,
    "sight": 10,
    "xp": 14,
    "radius": 0.55,
    "cooldown": 1.2,
    "windup": 0.35,
    "behavior": "hopper"
  },
  "chocobeetle": {
    "hp": 120,
    "damage": 13,
    "speed": 3.2,
    "reach": 1.5,
    "sight": 10,
    "xp": 24,
    "radius": 0.75,
    "cooldown": 2.4,
    "windup": 0.6,
    "behavior": "charger"
  },
  "gingerbread": {
    "hp": 850,
    "damage": 24,
    "speed": 2.6,
    "reach": 2.6,
    "sight": 13,
    "xp": 360,
    "radius": 1.4,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "seal": {
    "hp": 120,
    "damage": 13,
    "speed": 3,
    "reach": 1.5,
    "sight": 10,
    "xp": 24,
    "radius": 0.75,
    "cooldown": 2.4,
    "windup": 0.6,
    "behavior": "charger"
  },
  "owl": {
    "hp": 80,
    "damage": 11,
    "speed": 3.6,
    "reach": 1.4,
    "sight": 12,
    "xp": 20,
    "radius": 0.55,
    "cooldown": 1.1,
    "windup": 0.3,
    "behavior": "melee"
  },
  "mammoth": {
    "hp": 1100,
    "damage": 30,
    "speed": 2.4,
    "reach": 3,
    "sight": 13,
    "xp": 500,
    "radius": 1.8,
    "cooldown": 2.3,
    "windup": 0.6,
    "behavior": "boss"
  },
  "firebat": {
    "hp": 70,
    "damage": 11,
    "speed": 4.6,
    "reach": 1.4,
    "sight": 13,
    "xp": 20,
    "radius": 0.55,
    "cooldown": 2.2,
    "windup": 0.55,
    "behavior": "charger"
  },
  "magmacrab": {
    "hp": 160,
    "damage": 17,
    "speed": 2.6,
    "reach": 1.6,
    "sight": 9,
    "xp": 32,
    "radius": 0.8,
    "cooldown": 1.5,
    "windup": 0.5,
    "behavior": "melee"
  },
  "dragon": {
    "hp": 2600,
    "damage": 36,
    "speed": 3,
    "reach": 3,
    "sight": 18,
    "xp": 1400,
    "radius": 1.6,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "golem": {
    "hp": 1200,
    "damage": 32,
    "speed": 2.3,
    "reach": 2.7,
    "sight": 13,
    "xp": 600,
    "radius": 1.5,
    "cooldown": 2.2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "mushking": {
    "hp": 950,
    "damage": 24,
    "speed": 2.4,
    "reach": 2.7,
    "sight": 13,
    "xp": 320,
    "radius": 1.5,
    "cooldown": 2.2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "jellyqueen": {
    "hp": 1000,
    "damage": 25,
    "speed": 2.8,
    "reach": 2.6,
    "sight": 13,
    "xp": 400,
    "radius": 1.5,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "frostowl": {
    "hp": 1150,
    "damage": 28,
    "speed": 3.2,
    "reach": 2.6,
    "sight": 15,
    "xp": 520,
    "radius": 1.4,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "toysoldier": {
    "hp": 70,
    "damage": 9,
    "speed": 0,
    "reach": 11,
    "sight": 11,
    "xp": 16,
    "radius": 0.6,
    "cooldown": 1.9,
    "windup": 0.5,
    "behavior": "shooter"
  },
  "windmouse": {
    "hp": 80,
    "damage": 11,
    "speed": 3.6,
    "reach": 1.5,
    "sight": 11,
    "xp": 18,
    "radius": 0.6,
    "cooldown": 2.2,
    "windup": 0.6,
    "behavior": "charger"
  },
  "jackbox": {
    "hp": 90,
    "damage": 12,
    "speed": 2.8,
    "reach": 1.4,
    "sight": 9,
    "xp": 18,
    "radius": 0.6,
    "cooldown": 1.3,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "robot": {
    "hp": 900,
    "damage": 22,
    "speed": 2.4,
    "reach": 2.7,
    "sight": 13,
    "xp": 330,
    "radius": 1.5,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "monkey": {
    "hp": 110,
    "damage": 13,
    "speed": 0,
    "reach": 11,
    "sight": 12,
    "xp": 24,
    "radius": 0.6,
    "cooldown": 1.8,
    "windup": 0.5,
    "behavior": "shooter"
  },
  "snake": {
    "hp": 100,
    "damage": 14,
    "speed": 4.2,
    "reach": 1.5,
    "sight": 11,
    "xp": 24,
    "radius": 0.55,
    "cooldown": 2,
    "windup": 0.45,
    "behavior": "charger"
  },
  "chameleon": {
    "hp": 130,
    "damage": 15,
    "speed": 3.4,
    "reach": 1.6,
    "sight": 10,
    "xp": 30,
    "radius": 0.7,
    "cooldown": 1.4,
    "windup": 0.4,
    "behavior": "melee",
    "stealth": 5
  },
  "flytrap": {
    "hp": 150,
    "damage": 17,
    "speed": 0,
    "reach": 2.6,
    "sight": 7,
    "xp": 30,
    "radius": 0.8,
    "cooldown": 1.6,
    "windup": 0.5,
    "behavior": "rooted"
  },
  "gorilla": {
    "hp": 1000,
    "damage": 27,
    "speed": 2.8,
    "reach": 2.8,
    "sight": 14,
    "xp": 450,
    "radius": 1.6,
    "cooldown": 2.1,
    "windup": 0.6,
    "behavior": "boss"
  },
  "jellyzap": {
    "hp": 110,
    "damage": 14,
    "speed": 3.2,
    "reach": 1.4,
    "sight": 11,
    "xp": 28,
    "radius": 0.55,
    "cooldown": 2.2,
    "windup": 0.5,
    "behavior": "charger",
    "aquatic": true
  },
  "hammershark": {
    "hp": 170,
    "damage": 19,
    "speed": 4.4,
    "reach": 1.8,
    "sight": 12,
    "xp": 36,
    "radius": 0.9,
    "cooldown": 2.3,
    "windup": 0.6,
    "behavior": "charger",
    "aquatic": true
  },
  "urchin": {
    "hp": 160,
    "damage": 17,
    "speed": 0,
    "reach": 10,
    "sight": 10,
    "xp": 34,
    "radius": 0.7,
    "cooldown": 1.9,
    "windup": 0.5,
    "behavior": "shooter"
  },
  "leviathan": {
    "hp": 1150,
    "damage": 30,
    "speed": 2.8,
    "reach": 3,
    "sight": 15,
    "xp": 560,
    "radius": 1.8,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "cloudsheep": {
    "hp": 140,
    "damage": 16,
    "speed": 3,
    "reach": 1.4,
    "sight": 10,
    "xp": 34,
    "radius": 0.65,
    "cooldown": 1.3,
    "windup": 0.4,
    "behavior": "hopper"
  },
  "thunderbird": {
    "hp": 120,
    "damage": 18,
    "speed": 4.8,
    "reach": 1.4,
    "sight": 14,
    "xp": 36,
    "radius": 0.6,
    "cooldown": 2,
    "windup": 0.5,
    "behavior": "charger"
  },
  "windspirit": {
    "hp": 170,
    "damage": 19,
    "speed": 0,
    "reach": 12,
    "sight": 12,
    "xp": 40,
    "radius": 0.7,
    "cooldown": 1.7,
    "windup": 0.5,
    "behavior": "shooter"
  },
  "phoenix": {
    "hp": 1200,
    "damage": 32,
    "speed": 3.4,
    "reach": 2.8,
    "sight": 16,
    "xp": 620,
    "radius": 1.5,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "boss"
  },
  "wisp": {
    "hp": 130,
    "damage": 18,
    "speed": 3.8,
    "reach": 1.4,
    "sight": 16,
    "xp": 40,
    "radius": 0.55,
    "cooldown": 2,
    "windup": 0.5,
    "behavior": "charger",
    "stealth": 6
  },
  "spider": {
    "hp": 200,
    "damage": 22,
    "speed": 3.9,
    "reach": 1.7,
    "sight": 13,
    "xp": 46,
    "radius": 0.9,
    "cooldown": 1.3,
    "windup": 0.4,
    "behavior": "melee",
    "stealth": 7
  },
  "demoneye": {
    "hp": 190,
    "damage": 21,
    "speed": 0,
    "reach": 12,
    "sight": 14,
    "xp": 46,
    "radius": 0.8,
    "cooldown": 1.8,
    "windup": 0.5,
    "behavior": "shooter"
  },
  "shadowlord": {
    "hp": 1350,
    "damage": 34,
    "speed": 2.8,
    "reach": 2.9,
    "sight": 16,
    "xp": 800,
    "radius": 1.6,
    "cooldown": 2,
    "windup": 0.6,
    "behavior": "boss"
  }
};
for(const [id,rule] of Object.entries(combatRules))if(ENEMY_TYPES[id])Object.assign(ENEMY_TYPES[id],rule);
// Titans 0.75, forest hawks 0.5 (creature-sizes.ts): radius and reach follow the drawn size.
for(const id of Object.keys(SIZE_FACTORS))if(ENEMY_TYPES[id])ENEMY_TYPES[id]=sized(id,ENEMY_TYPES[id]);

/**
 * Size hierarchy (CC-05, RC-04): the reference's common creatures stand 0.60-0.74x its hero (hero 1.79 m; mushroom 1.14,
 * boar 1.16, bee 1.07, wolf 1.33). Our explorer stands 2.3 m x HERO_SCALE 0.84 = 1.93 m, and the species models were
 * 1.43-2.43 m tall (measured with speciesModel: mushroom 2.43, bunny 2.35, flowers/cactus/lollipop/urchin 2.12, jackbox 1.95,
 * blobs/bipeds/winged/frog/penguin 1.65, worms 1.62, eye 1.68, volcano 1.45, quadrupeds/crabs/turtle 1.43), so most stood
 * as tall as the explorer or taller. These scales bring every common creature to about 0.62x (small hoppers and fliers),
 * 0.67x (middling) or 0.73x (big brutes and rooted plants) of the explorer. Bosses keep their own 1.85 scale and are not
 * listed; the tiny magma slime that the magma slime splits into stays the smallest. Hit radii stay the reference's.
 */
export const ENEMY_SCALE:Readonly<Record<string,number>>={
  // Rare large quarry deliberately towers over the hero; ordinary common creatures retain their original sizes.
  forest_raptor:1.45,
  mushroom:.49,boar:.91,bee:.73,wolf:.99,chomper:.67,frog:.73,cactus:.67,crab:.99,
  jelly:.73,gummy:.91,lollipop:.61,bunny:.51,chocobeetle:.99,
  snowball:.73,penguin:.85,icebloom:.67,seal:.99,owl:.73,
  magmaslime:.85,minislime:.67,firelizard:.99,volcano:.89,firebat:.73,magmacrab:.99,magmaturtle:.99,lavaworm:.87,
  toysoldier:.78,windmouse:.84,jackbox:.72,
  monkey:.85,snake:.74,chameleon:.91,flytrap:.67,
  jellyzap:.78,hammershark:.99,urchin:.67,
  cloudsheep:.99,thunderbird:.85,windspirit:.78,
  wisp:.73,spider:.99,demoneye:.84,
};
/** The scale a creature's model is drawn at: bosses 1.85, common creatures their ENEMY_SCALE. */
export function enemyScale(type:string|undefined,boss=false){return (type&&Object.hasOwn(TITANS,type)?TITANS[type as keyof typeof TITANS].scale:boss?1.85:ENEMY_SCALE[type??'']??1)*sizeFactor(type);}
