/**
 * What helpers say while they work (friend-crew.ts shows it in a bubble above them). Original lines, a little funny
 * and cute, in pools of about twenty per scenario so repeats are rare; a LineBag deals them like cards (no repeat until
 * three quarters of a pool has been used). Vietnamese is in locales/vi-friend-lines.ts.
 */
import { TalkBag } from './house-talk.ts';

export type LineScenario = 'HARVEST' | 'PLANT' | 'COLLECT' | 'FEED' | 'COOK' | 'NICE' | 'HOME' | 'OUTFIT';
export const LINES: Record<LineScenario, string[]> = {
  HARVEST: [
    'Look at that one! Big and proud.',
    'Into the basket you go, little friend.',
    'Ripe at last. Good things come to those who wait five minutes.',
    'This one practically jumped into my hand.',
    'Another crop for the boss. I am on a roll!',
    'Smells like sunshine and soil. Lovely.',
    'Sorry, plant. Your holiday is over.',
    'Heavy! Somebody has been eating their vitamins.',
    'I only squeezed a little. Promise.',
    'One more for the pile. The pile is getting tall.',
    'That was the plumpest one all week.',
    'Snip, pull, done. Easy as pie. Pie is next, actually.',
    'The garden thanks you for the sunshine, and me for the pulling.',
    'Wow, the roots go all the way down. Impressive.',
    'This one is going straight to the top shelf.',
    'Did that carrot just wink at me?',
    'Harvest time! My favourite time. After lunch time.',
    'Careful, careful... got it! Not a single leaf torn.',
    'The garden is generous today.',
    'Fresh as a daisy, and much tastier.',
  ],
  PLANT: [
    'Tuck in, little seed. Sweet dreams.',
    'Grow tall, grow strong, grow quickly.',
    'A little water and a little hope. Done.',
    'Plant it, pat it, and wait five whole minutes.',
    'Not too deep, not too shallow. Just right.',
    'Welcome to the garden, new neighbour.',
    'I whispered a secret to it. It will not tell.',
    'Another bed full of promises.',
    'Do not peek, little seed. Growing takes time.',
    'Snug as a bug in a bed.',
    'That bed looks happy now.',
    'Plant, water, repeat. My kind of poetry.',
  ],
  COLLECT: [
    'Thank you, hens! Six eggs, all warm.',
    'Gently now... the cow is watching me.',
    'Fresh milk, still steaming. Best job ever.',
    'The duck gave me a very serious look and an egg.',
    'Look at the size of this one!',
    'Truffles! The pig has a gift for finding them.',
    'Thank you, friend. Same time tomorrow?',
    'Careful, careful, do not drop it. Do not drop it.',
    'The pen is spotless and the baskets are full.',
    'I hummed a tune and the hens joined in. Sort of.',
    'One for the boss, one for the chest, none for me.',
    'Hello, little one. Yes, you are all very good animals.',
    'Warm eggs on a cold day. Joy!',
    'That cow is the queen of the barn, I am sure of it.',
    'Collected, counted and cuddled.',
    'Not a single crack in this batch.',
    'The goose... I mean the duck... says hello.',
    'Everyone is fed, everyone is happy.',
    'I will be back with the bucket soon.',
    'Farm life is the good life.',
  ],
  FEED: [
    'Lunch is served, everybody!',
    'Slowly, slowly, there is plenty for all.',
    'Eat up, you lovely things.',
    'No pushing! The cow goes first.',
    'The pig has finished already and is looking at mine.',
    'Crunch crunch crunch. The best sound.',
    'A full tummy makes a happy animal.',
    'I always leave one for the boss.',
    'Nom nom. Wait, that was supposed to be the animals.',
    'Everyone gets a share. Fair and square.',
    'Look at them go! Eating champions.',
    'Fed, watered and fluffed.',
  ],
  COOK: [
    'Lovely, that goes straight in the pot.',
    'Ingredients, assemble!',
    'I can already taste tonight\'s dinner.',
    'Fresh and crisp. Chef\'s kiss.',
    'This will go perfectly with a little salt.',
    'Half for the pot, half for the boss. Fair deal.',
    'If it smells this good raw, imagine cooked.',
    'Soup, stew or pie? Decisions, decisions.',
    'My apron is already full of treasure.',
    'Do not tell the pot I am late. It gets grumpy.',
    'A cook never wastes a good ingredient.',
    'Cooking is mostly choosing the right things to eat on the way.',
    'Mmm, one tiny taste test. For science.',
    'Pepper, you are a genius. Pepper is me.',
    'These will make the stew sing.',
    'Straight from the garden to my basket.',
    'The kitchen is going to smell amazing.',
    'I have got a good feeling about this dish.',
    'Basket full. Time to stir.',
    'Gather first, cook second, eat third.',
  ],
  NICE: [
    'Hi boss! You look great today.',
    'Good to see you, boss. The garden loves you.',
    'You work so hard. We are proud of you.',
    'Thank you for rescuing us, boss. Best day ever.',
    'Everything is under control. You can relax.',
    'Your boots are very shiny today.',
    'I saved you the best one. Do not tell the others.',
    'You make this village feel like home.',
    'Have you eaten? You should eat. I can cook!',
    'Nice weather for adventures, boss.',
    'I like working for you. The boss is kind.',
    'If you are tired, the sofa is waiting.',
    'That is a very good hat you are wearing.',
    'The animals asked about you. They miss your hugs.',
    'Smile, boss! The day is good.',
    'I would follow you to the moon. Bring snacks though.',
    'You are the best explorer in the whole world.',
    'Take a deep breath. Smell that? That is our garden.',
    'Thanks for the energy, boss. It keeps us going!',
    'We are a good team, you and me.',
  ],
  HOME: [
    'Time to pop home for a moment.',
    'I will be right back. Do not miss me too much.',
    'Home break! Feet up, nose in a cup of tea.',
    'Nature calls. Home calls too.',
    'Just going to put these things away.',
    'A quick rest and then back to work.',
    'The kettle has been calling my name.',
    'I am off to the cottage. Save me a seat.',
    'Even helpers need a cosy moment.',
    'Going in to warm up by the fire.',
    'Back in a minute, I promise.',
    'Oh, I think I left the soup on.',
    'Home sweet home, here I come.',
    'Quick snack and a sit-down.',
    'Do not go anywhere without me!',
    'I will freshen up and be right out.',
    'The cottage looks so inviting from here.',
    'Break time! The best part of any job.',
    'I need a minute with the sofa.',
    'See you soon, garden!',
  ],
  OUTFIT: [
    'New clothes, new me!',
    'Ta-da! What do you think of this one?',
    'I tried on everything. This is the winner.',
    'A fresh outfit for fresh work.',
    'Do I look fancy? I feel fancy.',
    'The mirror said yes. The mirror is never wrong.',
    'Clean, fresh and ready to cook.',
    'That old outfit was getting tired.',
    'Everything goes with a good attitude.',
    'A hat makes a day.',
    'Do not tell the soup I changed.',
    'Boss, your wardrobe is amazing!',
  ],
};
import { MORE_LINES } from "./friend-lines-more.ts";
for (const k of Object.keys(LINES) as LineScenario[]) LINES[k].push(...MORE_LINES[k].map(p => p[0]));
const bag = new TalkBag();
/** One line for the scenario, from its own shuffled-like pool. `who` keeps each helper's own recent lines apart. */
export const lineFor = (who: string, scenario: LineScenario, random = Math.random) => bag.pick(who + ':' + scenario, LINES[scenario], random);
